---
abstract: "Add line numbers to eval'ed heredoc blocks"
author:
  - 'David Muir Sharnoff <cpan@dave.sharnoff.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Eval-LineNumbers
no_index:
  directory:
    - t
    - inc
requires:
  Exporter: 5.57
resources:
  repository: http://github.com/muir/Eval-LineNumbers
version: 0.34
